spring.application.name=placement-tracker
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

groq.api.key=${api_key}
server.port=${PORT:8080}

